/*------------------------------------------------------------------------------------------
:*                       INSTITUTO TECNOLOGICO DE LA LAGUNA
:*                     INGENIERIA EN SISTEMAS COMPUTACIONALES
:*                       TOPICOS AVANZADOS DE PROGRAMACION "B"
:*
:*                   SEMESTRE: ENE-JUN/2019    HORA: 17-18 HRS
:*
:*                        Crear un Calatalogo de Apps Anteriores
:*        
:*  Archivo     : prismasApp.java
:*  Autor       : Enrique Antonio Belmarez Meraz     17130765
:*  Fecha       : 22/MAY/2019
:*  Compilador  : JAVA J2SE v1.8.0
:*  Descripción : Crear un catalogo de multiple seleccion para las aplicaciones
:*                creadas en las unidades pasadas:
:*                 *Editor App.
:*                 *PrismasApp
:*                 *Matematicas App
:*                 *Conversiones App
:*                 *Figuras Geometricas App 

:*  Ultima modif:
:*  Fecha       Modificó             Motivo
:*==========================================================================================*/
package Catalogo;


import Editor.Imagenes;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import prismas.SplashFrame;

/**
 *
 * @author ebelm
 */
public class CatalogoFrame extends javax.swing.JFrame {

/*----------------------------------------------------------------------------------------*/
//constructor
    public CatalogoFrame() {
        initComponents();
        setSize(800,700);
        setLocationRelativeTo(null);
        setResizable(false);
        setBackground(Color.LIGHT_GRAY);
        
        // icono matematicas
        ImageIcon imgIconmatematicas = new ImageIcon (
            getClass (). getResource("/iconos/matematicas.jpg") );
        Image mate = imgIconmatematicas.getImage();   
        Image mateselected = imgIconmatematicas.getImage();
        mate = Imagenes.getScaledImage(mate, 200, 200);  
        mateselected = Imagenes.getScaledImage( mateselected, 230, 230);
        btnMatematicas.setIcon( new ImageIcon( mate) );
        btnMatematicas.setSelectedIcon(new ImageIcon( mateselected) );
        
        // icono figuras
        ImageIcon imgIconfiguras = new ImageIcon (
            getClass (). getResource("/iconos/figurasGeometricas.jpg") );
        Image figu = imgIconfiguras.getImage();   
        Image figuselected = imgIconfiguras.getImage();
        figu = Imagenes.getScaledImage(figu, 200, 200);  
        figuselected = Imagenes.getScaledImage( figuselected, 230, 230);
        btnFigurasGeometricas.setIcon( new ImageIcon( figu) );
        btnFigurasGeometricas.setSelectedIcon(new ImageIcon( figuselected) );
        
        // icono convesiones
        ImageIcon imgIconvesiones = new ImageIcon (
            getClass (). getResource("/iconos/conversiones.png") );
        Image conve = imgIconvesiones.getImage();   
        Image conveselected = imgIconvesiones.getImage();
        conve = Imagenes.getScaledImage(conve, 200, 200);  
        conveselected = Imagenes.getScaledImage( conveselected, 230, 230);
        btnConversiones.setIcon( new ImageIcon( conve) );
        btnConversiones.setSelectedIcon(new ImageIcon( conveselected) );
        
        // icono editor
        ImageIcon imgIconeditor = new ImageIcon (
            getClass (). getResource("/iconos/EditorTexto.png") );
        Image editor = imgIconeditor.getImage();   
        Image editorselected = imgIconeditor.getImage();
        editor = Imagenes.getScaledImage(editor, 200, 200);  
        editorselected = Imagenes.getScaledImage( editorselected, 230, 230);
        btnEditordeTexto.setIcon( new ImageIcon( editor) );
        btnEditordeTexto.setSelectedIcon(new ImageIcon( editorselected) );
        
        // icono prisma
        ImageIcon imgIconprisma = new ImageIcon (
            getClass (). getResource("/iconos/prismas.jpg") );
        Image prisma = imgIconprisma.getImage();   
        Image prismaselected = imgIconprisma.getImage();
        prisma = Imagenes.getScaledImage(prisma, 200, 200);  
        prismaselected = Imagenes.getScaledImage( prismaselected, 230, 230);
        btnPrismas.setIcon( new ImageIcon( prisma) );
        btnPrismas.setSelectedIcon(new ImageIcon( prismaselected) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMatematicas = new javax.swing.JButton();
        btnFigurasGeometricas = new javax.swing.JButton();
        btnConversiones = new javax.swing.JButton();
        btnEditordeTexto = new javax.swing.JButton();
        btnPrismas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmniSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmniAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo de Apps");

        btnMatematicas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMatematicas.setText("Matematicas");
        btnMatematicas.setToolTipText("App para Calcular el factorial , las combinaciones y permutaciones");
        btnMatematicas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatematicas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMatematicas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnMatematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatematicasActionPerformed(evt);
            }
        });

        btnFigurasGeometricas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFigurasGeometricas.setText("Figuras Geometricas");
        btnFigurasGeometricas.setToolTipText("App para calcular el area y perimetro de algunas figuras");
        btnFigurasGeometricas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFigurasGeometricas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFigurasGeometricas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnFigurasGeometricas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFigurasGeometricasActionPerformed(evt);
            }
        });

        btnConversiones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConversiones.setText("Conversiones");
        btnConversiones.setToolTipText("App para calcular algunas convesiones de la vida cotidiana");
        btnConversiones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConversiones.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnConversiones.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnConversiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversionesActionPerformed(evt);
            }
        });

        btnEditordeTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEditordeTexto.setText("Editor de Texto");
        btnEditordeTexto.setToolTipText("App para escribir texto y guardarlos ");
        btnEditordeTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditordeTexto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnEditordeTexto.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnEditordeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditordeTextoActionPerformed(evt);
            }
        });

        btnPrismas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrismas.setText("Prismas");
        btnPrismas.setToolTipText("App para calcular algunos prismas comunes");
        btnPrismas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrismas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPrismas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPrismas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrismasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CATALOGO DE APLICACIONES");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("Archivo");

        jmniSalir.setText("Salir");
        jmniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmniSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jmniAcercade.setText("Acerca de..");
        jmniAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniAcercadeActionPerformed(evt);
            }
        });
        jMenu2.add(jmniAcercade);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMatematicas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFigurasGeometricas))
                            .addComponent(btnEditordeTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrismas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConversiones)
                                .addGap(0, 220, Short.MAX_VALUE)))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConversiones)
                    .addComponent(btnFigurasGeometricas)
                    .addComponent(btnMatematicas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditordeTexto)
                    .addComponent(btnPrismas))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*----------------------------------------------------------------------------------------*/
//boton para abrir el frame de matematicas
    private void btnMatematicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatematicasActionPerformed
        matematicas.SplashFrame m = new matematicas.SplashFrame();
        m.setVisible(true);
    }//GEN-LAST:event_btnMatematicasActionPerformed
/*----------------------------------------------------------------------------------------*/
//boton para abrir el frame de Figuras Geometricas
    private void btnFigurasGeometricasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFigurasGeometricasActionPerformed
      FigurasGeometricas.SplashFrame f = new FigurasGeometricas.SplashFrame();
      f.setVisible(true);
    }//GEN-LAST:event_btnFigurasGeometricasActionPerformed
/*----------------------------------------------------------------------------------------*/
//boton para abrir el frame de Conversiones
    private void btnConversionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversionesActionPerformed
     conversiones.SplashFrame c = new conversiones.SplashFrame();
     c.setVisible(true);
    }//GEN-LAST:event_btnConversionesActionPerformed
/*----------------------------------------------------------------------------------------*/
//boton para abrir el frame de Editor de Texto
    private void btnEditordeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditordeTextoActionPerformed
    Editor.SplashFrame e = new Editor.SplashFrame();
    e.setVisible(true);        
    }//GEN-LAST:event_btnEditordeTextoActionPerformed
/*----------------------------------------------------------------------------------------*/
//boton para abrir el frame de Prismas
    private void btnPrismasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrismasActionPerformed
       prismas.SplashFrame p = new SplashFrame();
       p.setVisible(true);
    }//GEN-LAST:event_btnPrismasActionPerformed
/*----------------------------------------------------------------------------------------*/
//boton para salir de la aplicacion
    private void jmniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniSalirActionPerformed
       dispose();
    }//GEN-LAST:event_jmniSalirActionPerformed
/*----------------------------------------------------------------------------------------*/
//boton para abrir el frame de Acerca De
    private void jmniAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniAcercadeActionPerformed
        AcercaDeDialog a = new AcercaDeDialog(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_jmniAcercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConversiones;
    private javax.swing.JButton btnEditordeTexto;
    private javax.swing.JButton btnFigurasGeometricas;
    private javax.swing.JButton btnMatematicas;
    private javax.swing.JButton btnPrismas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmniAcercade;
    private javax.swing.JMenuItem jmniSalir;
    // End of variables declaration//GEN-END:variables
}
